spring.application.name=billme-backend
spring.datasource.url=jdbc:mysql://localhost:3306/billme_db
spring.datasource.username=root
spring.datasource.password=699123s@
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

server.port=8080
razorpay.key-id=rzp_test_SIgyziHVJLgRT2
razorpay.webhook-secret=billme_webhook_secret

processing.fee.percent=2
platform.withdrawal.fee-percent=2

app.admin.bootstrap.enabled=${ADMIN_BOOTSTRAP:false}
app.admin.bootstrap.email=${ADMIN_EMAIL:}
app.admin.bootstrap.password=${ADMIN_PASSWORD:}

spring.jpa.open-in-view=false
razorpay.key-secret=${RAZORPAY_KEY_SECRET}
spring.mail.host=${SMTP_HOST}
spring.mail.port=${SMTP_PORT}
spring.mail.username=${SMTP_USERNAME}
spring.mail.password=${SMTP_PASSWORD}
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true

app.payment.url=http://localhost:5173/pay